SaiGonSoftware/Awesome-CMS-Core

src/AwesomeCMSCore/AwesomeCMSCore/Migrations/20180317151022_InitDB_20181703_221002.Designer.cs, src/AwesomeCMSCore/AwesomeCMSCore/Migrations/20180317151022_InitDB_20181703_221002.cs, src/AwesomeCMSCore/AwesomeCMSCore/log.txt, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Controllers/API/TagController.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Controllers/TagController.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Services/ITagService.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Services/TagService.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Data/ApplicationDbContext.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Entities/BaseEntity.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Entities/Tag.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Helper/Filter/ValidModelAttribute.cs
* Implement Add for tag services.
* Add valid model helper
* Init value for base class
=> ACC-create-tag-page

src/AwesomeCMSCore/AwesomeCMSCore/webpack.config.js, src/AwesomeCMSCore/AwesomeCMSCore/wwwroot/frontend/js/App/Common/AwesomeInput.jsx
=> ACC-package-upgrade

src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Services/TagService.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Repositories/GenericRepository.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Repositories/IUnitOfWork.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Repositories/UnitOfWork.cs
=> ACC-unit-of-work

src/AwesomeCMSCore/AwesomeCMSCore/AwesomeCMSCore.csproj, src/AwesomeCMSCore/AwesomeCMSCore/Extension/ApplicationBuilderExtensions.cs, src/AwesomeCMSCore/AwesomeCMSCore/Extension/ServiceCollectionExtensions.cs, src/AwesomeCMSCore/AwesomeCMSCore/Startup.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Account/Controllers/API/AccountController.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Controllers/API/TagController.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Controllers/PortalController.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Controllers/TagController.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Client/Controllers/HomeController.cs
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/103
=> ACC-swagger Add swagger ui

src/AwesomeCMSCore/AwesomeCMSCore/AwesomeCMSCore.csproj, src/AwesomeCMSCore/AwesomeCMSCore/Extension/ApplicationBuilderExtensions.cs, src/AwesomeCMSCore/AwesomeCMSCore/Extension/ServiceCollectionExtensions.cs, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Helper/envConfig.js, src/AwesomeCMSCore/AwesomeCMSCore/Startup.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Account/AwesomeCMSCore.Modules.Account.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Account/Controllers/API/V1/AccountController.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Account/Controllers/API/V2/AccountController.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/AwesomeCMSCore.Modules.Admin.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Controllers/API/V1/TagController.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Client/AwesomeCMSCore.Modules.Client.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Helper/Controllers/ErrorController.cs
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/127
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/123
Add api versioning for API and Swagger
=> ACC-api-versioning

src/AwesomeCMSCore/AwesomeCMSCore/AwesomeCMSCore.csproj, src/AwesomeCMSCore/AwesomeCMSCore/Startup.cs, src/AwesomeCMSCore/AwesomeCMSCore/appsettings.Development.json, src/AwesomeCMSCore/AwesomeCMSCore/appsettings.json
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/119
Use app secrect
=> ACC-user-secret

src/AwesomeCMSCore/AwesomeCMSCore/Extension/ApplicationBuilderExtensions.cs, src/AwesomeCMSCore/AwesomeCMSCore/Extension/ServiceCollectionExtensions.cs, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Helper/ajax.js
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/137
store single refresh_token and set expire time for cookie
=> ACC-clean-up

src/AwesomeCMSCore/AwesomeCMSCore/Extension/ServiceCollectionExtensions.cs, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Helper/StatusCode.js, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Account/LoginForm.jsx, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Account/Controllers/API/V1/AccountController.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Helper/Enum/ACCStatusCode.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Helper/Enum/AccAppEnum.cs
=> add more status code and handle lockout and email confirm when login

src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Helper/util.js, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Account/Index.jsx
=> ACC-rerender

src/AwesomeCMSCore/AwesomeCMSCore.Infrastructure/AwesomeCMSCore.Infrastructure.csproj, src/AwesomeCMSCore/AwesomeCMSCore.sln, src/AwesomeCMSCore/AwesomeCMSCore/AwesomeCMSCore.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Account/AwesomeCMSCore.Modules.Account.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Account/Views/Account/ConfirmEmail.cshtml, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Account/Views/Account/Register.cshtml, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Account/Views/_ViewImports.cshtml, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/AwesomeCMSCore.Modules.Admin.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Client/AwesomeCMSCore.Modules.Client.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Client/Views/_ViewImports.cshtml, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Email/AwesomeCMSCore.Modules.Email.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/AwesomeCMSCore.Modules.Entities.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Entities/PasswordRequest.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Helper/AwesomeCMSCore.Modules.Helper.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Helper/Enum/AppEnum.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Helper/Extensions/RandomString.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Mapper/AwesomeCMSCore.Modules.Mapper.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Queue/AwesomeCMSCore.Modules.Queue.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Repositories/AwesomeCMSCore.Modules.Repositories.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.WebJob/AwesomeCMSCore.Modules.WebJob.csproj
=> ACC-Nuget 

.gitignore, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Helper/API_Endpoint/AccountEndpoint.js, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Helper/API_Endpoint/PortalEndpoint.js, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Helper/API_Endpoint/PostOptionEndpoint.js, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Helper/API_Endpoint/RoleEndpoint.js, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Helper/Enviroment.js, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Helper/Http.js, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Helper/QueryStringParser.js, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Account/Index.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Account/Login/LoginForm.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Account/Manage/AddUserModal.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Account/Manage/EditUserRolesModal.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Account/Manage/ManageRolesModal.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Account/Password/ForgotPassword.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Account/Password/ResetPassword.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Categories/CategoriesCreateContainer.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Tag/TagCreateContainer.jsx, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Account/Controllers/API/V1/AccountController.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Account/Controllers/API/V1/RolesController.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Account/Repositories/AccountRepository.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Account/Repositories/IAccountRepository.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Controllers/API/V1/PostOptionsController.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Helper/Services/UserService.cs
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/161
Clean up API endpoint
=> ACC-api-endpoint

src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Account/Manage/ManageRolesModal.jsx, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Account/Repositories/AccountRepository.cs
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/160
=> Add db transaction for async service

src/AwesomeCMSCore/AwesomeCMSCore/AwesomeCMSCore.csproj, src/AwesomeCMSCore/AwesomeCMSCore/Extension/ServiceCollectionExtensions.cs, src/AwesomeCMSCore/AwesomeCMSCore/Startup.cs, src/AwesomeCMSCore/AwesomeCMSCore/appsettings.Development.json, src/AwesomeCMSCore/AwesomeCMSCore/appsettings.json, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Helper/Services/ICacheService.cs
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/169
Add redis cache
=> Acc-redis-cache

src/AwesomeCMSCore/AwesomeCMSCore/Migrations/20180729113038_InitDB_20182907_183020.Designer.cs, src/AwesomeCMSCore/AwesomeCMSCore/Migrations/20180729113038_InitDB_20182907_183020.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Entities/Post.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Enums/PostStatus.cs
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/189
=> Add post status enum

src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Common/ACCButton/ACCButton.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Post/PostDetail.jsx, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/AwesomeCMSCore.Modules.Admin.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Repositories/PostRepository.cs
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/188
Edit post
=> ACC-post-page

src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Helper/API_Endpoint/PostEndpoint.js, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Helper/Http.js, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Post/PostContainer.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Post/PostDetail.jsx
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/193
=> ACC-post-page: Delete post

src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Account/Index.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Account/Login/LoginForm.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Account/Manage/AddUserModal.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Account/Manage/EditUserRolesModal.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Account/Manage/ManageRolesModal.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Account/Password/ForgotPassword.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Account/Password/ResetPassword.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Categories/CategoriesCreateContainer.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Post/NewPost.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Post/PostContainer/PostContainer.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Post/PostContainer/PostContainerDetail.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Post/PostDetail.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Tag/TagCreateContainer.jsx, src/AwesomeCMSCore/AwesomeCMSCore/webpack.config.js, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Controllers/API/V1/CommentController.cs
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/186
=> Cleanup import in react app

src/AwesomeCMSCore/AwesomeCMSCore/React/css/Admin/Comments/CommentContainerBody.scss, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Comment/CommentActions.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Comment/CommentContainer.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Comment/CommentContainerBody.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Post/PostContainer/PostContainer.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Post/PostDetail.jsx
A description of the changes proposed in the pull request.
+ In memory update state for approved comment
=> ACC-comment

src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Comment/CommentActions.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Comment/CommentContainer.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Comment/CommentContainerBody.jsx
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/244
Spam comment
=> Spam comment

src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Account/Login/LoginForm.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Comment/CommentActions.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Comment/CommentContainer.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Comment/CommentContainerBody.jsx
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/246
Delete comment
=> [Acc-Comment] Delete comment

src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Comment/CommentActions.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Comment/CommentContainer.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Comment/CommentContainerBody.jsx
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/248
Reply comment in Admin portal
=> ACC-Comment: Reply comment in Admin portal

src/AwesomeCMSCore/AwesomeCMSCore/React/.editorconfig, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Controllers/API/V1/CommentController.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Repositories/CommentRepository.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Repositories/ICommentRepository.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/ViewModels/CommentReplyViewModel.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Entities/Comment.cs
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/250
add api to reply comment
=> ACC-comment: Add api to reply comment

src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Comment/CommentContainer.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Comment/CommentContainerBody.jsx, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Repositories/CommentRepository.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/ViewModels/CommentReplyViewModel.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Data/SeedData.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Entities/Comment.cs
update db design wih api to reply comment
=> ACC-Comment: Update db design wih api to reply comment

src/AwesomeCMSCore/AwesomeCMSCore/AwesomeCMSCore.csproj, src/AwesomeCMSCore/AwesomeCMSCore/Extension/ServiceCollectionExtensions.cs, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Comment/CommentContainer.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Comment/CommentContainerBody.jsx, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Repositories/CommentRepository.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/ViewModels/CommentReplyViewModel.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Email/EmailOptions.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Email/EmailSender.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Email/EmailType.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Data/ApplicationDbContext.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Data/SeedData.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Entities/Comment.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Entities/Media.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Entities/Post.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Entities/PostOption.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Entities/User.cs
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/254
Email notification when user reply comment
=> ACC-Comment:  Email notification when user reply comment 

src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Repositories/CommentRepository.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/ViewModels/CommentViewModel.cs
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/260
Refactor to hide sensitive user data
=> ACC-refactor refactor to hide sensitive user data

src/AwesomeCMSCore/AwesomeCMSCore/Extension/ServiceCollectionExtensions.cs
Minor refactor change from transient to scoped
=> ACC-refactor: Minor refactor change from transient to scoped

src/AwesomeCMSCore/AwesomeCMSCore/React/css/Admin/Post/PostContainer.scss, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Post/PostContainer/PostContainerDetail.jsx
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/270
=> Add views for post in admin page

src/AwesomeCMSCore/AwesomeCMSCore/package.json, src/AwesomeCMSCore/AwesomeCMSCore/postcss.config.js, src/AwesomeCMSCore/AwesomeCMSCore/webpack.config.js
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/278
Optimize bundle size for css
=> ACC-webpack: Optimize bundle size for css

src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Repositories/PostOptionsRepository.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Repositories/PostRepository.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Client/Repositories/PostRepository.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Data/SeedData.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Entities/PostOption.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Enums/PostOptionType.cs
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/287
Refactor change compare string to int
=> ACC-Refactor 

src/AwesomeCMSCore/AwesomeCMSCore/AwesomeCMSCore.csproj, src/AwesomeCMSCore/AwesomeCMSCore/Program.cs, src/AwesomeCMSCore/AwesomeCMSCore/nlog.config, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Client/Controllers/HomeController.cs
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/269
Add logger
=> ACC-log-integration: Add NLog

src/AwesomeCMSCore/AwesomeCMSCore.sln, src/AwesomeCMSCore/AwesomeCMSCore/AwesomeCMSCore.csproj, src/AwesomeCMSCore/AwesomeCMSCore/Extension/ServiceCollectionExtensions.cs, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Client/Shared/NewsLetter.jsx, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Account/Repositories/AccountRepository.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Client/Controllers/API/V1/HomeController.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Data/ApplicationDbContext.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Entities/NewsLetter.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Shared/AwesomeCMSCore.Modules.Shared.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Shared/Controllers/V1/NewsLetterController.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Shared/Repositories/INewsLetterRepository.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Shared/Repositories/NewsLetterRepository.cs
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/293
API for email subscription
=> Acc-client-ui:  API for email subscription

src/AwesomeCMSCore/AwesomeCMSCore/React/css/Client/client.scss, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Helper/API_Endpoint/EmailEndpoint.js, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Helper/appEnum.js, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Comment/CommentActions.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Comment/CommentContainer.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Comment/CommentContainerBody.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Client/Shared/NewsLetter.jsx, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Helper/Enum/AppStatusCode.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Shared/Controllers/V1/NewsLetterController.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Shared/Models/EmailRegisterModel.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Shared/Repositories/INewsLetterRepository.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Shared/Repositories/NewsLetterRepository.cs
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/265
NEWSLETTER subscribe
=> ACC-client-ui NEWSLETTER subscribe

src/AwesomeCMSCore/AwesomeCMSCore.sln, src/AwesomeCMSCore/AwesomeCMSCore/AwesomeCMSCore.csproj, src/AwesomeCMSCore/AwesomeCMSCore/Extension/ServiceCollectionExtensions.cs, src/AwesomeCMSCore/AwesomeCMSCore/Startup.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Background/AwesomeCMSCore.Modules.Background.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Scheduled/AwesomeCMSCore.Modules.Scheduled.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Scheduled/ConsumeScopedServiceHostedService.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Scheduled/ScopedProcessingService.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Scheduled/TimedHostedService.cs
=> Add Background Service

.travis.yml, src/AwesomeCMSCore/AwesomeCMSCore.Infrastructure/AwesomeCMSCore.Infrastructure.csproj, src/AwesomeCMSCore/AwesomeCMSCore/AwesomeCMSCore.csproj, src/AwesomeCMSCore/AwesomeCMSCore/Extension/ServiceCollectionExtensions.cs, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Client/Index/Post/PostList.jsx, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Account/AwesomeCMSCore.Modules.Account.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/AwesomeCMSCore.Modules.Admin.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Background/AwesomeCMSCore.Modules.Background.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Client/AwesomeCMSCore.Modules.Client.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Email/AwesomeCMSCore.Modules.Email.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/AwesomeCMSCore.Modules.Entities.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Helper/AwesomeCMSCore.Modules.Helper.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Mapper/AwesomeCMSCore.Modules.Mapper.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Queue/AwesomeCMSCore.Modules.Queue.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Repositories/AwesomeCMSCore.Modules.Repositories.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Scheduled/AwesomeCMSCore.Modules.Scheduled.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Shared/AwesomeCMSCore.Modules.Shared.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.WebJob/AwesomeCMSCore.Modules.WebJob.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.WebJobRunner/AwesomeCMSCore.Modules.WebJobRunner.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.WebJobRunner/Program.cs
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/298
Upgrade to .Net Core 2.2
=> ACC-NetCore2.2 Upgrade to .Net Core 2.2

.gitattributes
=> Acc language detection

.gitattributes, src/AwesomeCMSCore/AwesomeCMSCore/AwesomeCMSCore.csproj, src/AwesomeCMSCore/AwesomeCMSCore/Extension/ServiceCollectionExtensions.cs
=> Acc upgrade

src/AwesomeCMSCore/AwesomeCMSCore/Extension/ServiceCollectionExtensions.cs, src/AwesomeCMSCore/AwesomeCMSCore/Startup.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Scheduled/IScheduledEmailService.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Scheduled/ScheduledEmailService.cs
https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/issues/304
Send email using scheduled job
=> Acc-scheduled-job

src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Data/ApplicationDbContext.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Entities/Settings.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Enums/SettingKey.cs
=> ACC-cron-expression Add Setting table

src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Helper/API_Endpoint/AccountEndpoint.js, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Account/AwesomeCMSCore.Modules.Account.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Account/Controllers/API/V1/AccountController.cs
=> Fix login for admin

src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Client/Index/Post/PostList.jsx, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Repositories/PostRepository.cs
Fixed when saving a new post without categories or thumbnail. 
They weren't checked.
=> No image and no categories check

Readme.md, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Post/PostDetail.jsx, src/AwesomeCMSCore/AwesomeCMSCore/migrate.bat, src/AwesomeCMSCore/AwesomeCMSCore/package.json, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Repositories/PostRepository.cs
Fixed my contribution profile link.
Upgraded node-sass.
Fixed migration batch creating corrupted file names with some localizations. (EF already add a timestamp).
Fixed automapper creating new instance of Post entity that prevent the post from saving.
Other post null media check.****
=> Various fixes

src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/AwesomeCMSCore.Modules.Admin.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Repositories/PostRepository.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Services/AssetService.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Client/Controllers/HomeController.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Queue/Services/IQueueService.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Queue/Services/QueueService.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Queue/Settings/QueueSettings.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.WebJobRunner/AwesomeCMSCore.Modules.WebJobRunner.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.WebJobRunner/Program.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.WebJobRunner/WebJob.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.WebJobRunner/appsettings.json
https://github.com/SaiGonSoftware/Awesome-CMS-Core/issues/340
=> Init background process service using rabbitmq

src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Client/Index/Post/PostContainer.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Client/Index/Post/PostList.jsx, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/ViewModels/PostListViewModel.cs
https://github.com/SaiGonSoftware/Awesome-CMS-Core/issues/347
Get image for index page
=> ACC-thumbnail: Get image for index page

src/AwesomeCMSCore/.vs/config/applicationhost.config, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Client/Index/Post/PostList.jsx, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/ViewModels/PostListViewModel.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Client/Repositories/PostRepository.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Data/SeedData.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Entities/Post.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.WebJobRunner/WebJob.cs
https://github.com/SaiGonSoftware/Awesome-CMS-Core/issues/352
=> Load PostOption in Client UI

src/AwesomeCMSCore/AwesomeCMSCore/AwesomeCMSCore.csproj, src/AwesomeCMSCore/AwesomeCMSCore/Extension/ApplicationBuilderExtensions.cs, src/AwesomeCMSCore/AwesomeCMSCore/Extension/ServiceCollectionExtensions.cs, src/AwesomeCMSCore/AwesomeCMSCore/Startup.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Email/AwesomeCMSCore.Modules.Email.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/AwesomeCMSCore.Modules.Entities.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.GoogleDriveAPI/AwesomeCMSCore.Modules.GoogleDriveAPI.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Repositories/AwesomeCMSCore.Modules.Repositories.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Scheduled/AwesomeCMSCore.Modules.Scheduled.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.WebJobRunner/AwesomeCMSCore.Modules.WebJobRunner.csproj, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.WebJobRunner/WebJob.cs
=> Upgrade package

src/AwesomeCMSCore/AwesomeCMSCore/Extension/ServiceCollectionExtensions.cs, src/AwesomeCMSCore/AwesomeCMSCore/Startup.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Mapper/CommentProfile.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Mapper/PostOptionsProfile.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Mapper/PostProfile.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Mapper/UserProfile.cs
https://github.com/SaiGonSoftware/Awesome-CMS-Core/issues/362
=> Fix automapper error when deploy to azure

src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Client/Index/Post/PostContainer.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Client/Shared/Social.jsx, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Client/Repositories/PostRepository.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Client/ViewModels/PostViewModel.cs
https://github.com/SaiGonSoftware/Awesome-CMS-Core/issues/366
https://github.com/SaiGonSoftware/Awesome-CMS-Core/issues/367
=> ACC-social-profile-settings

src/AwesomeCMSCore/AwesomeCMSCore/React/css/Client/theme.default.scss, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Helper/util.js, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/admin.js, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Shared/SocialLink.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/EntryPoint/Modules/Shared/SocialLinks.js, src/AwesomeCMSCore/AwesomeCMSCore/Views/Shared/_ClientFooter.cshtml, src/AwesomeCMSCore/AwesomeCMSCore/Views/Shared/_ClientHeader.cshtml, src/AwesomeCMSCore/AwesomeCMSCore/Views/Shared/_ClientLayout.cshtml, src/AwesomeCMSCore/AwesomeCMSCore/webpack.config.js, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Controllers/API/V1/SettingsController.cs
=> Style social link

src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Common/ACCInput/ACCEditor.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Helper/API_Endpoint/SettingsEndpoint.js, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Helper/util.js, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Account/Login/LoginForm.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Account/Password/ForgotPassword.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Account/Password/ResetPassword.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Post/NewPost.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Post/PostDetail.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Settings/AdminSettingsContainer.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Admin/Settings/Profile/UserProfileSetting.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Client/Index/Post/PostContainer.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Modules/Client/Shared/AuthorDetail.jsx, src/AwesomeCMSCore/AwesomeCMSCore/React/js/App/Shared/SocialLinks.jsx, src/AwesomeCMSCore/AwesomeCMSCore/Views/Shared/_ClientHeader.cshtml, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Controllers/API/V1/SettingsController.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Repositories/ISettingsRepository.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Repositories/SettingsRepository.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/ViewModels/ProfileSetting.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Client/Repositories/PostRepository.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Client/ViewModels/PostViewModel.cs, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Entities/Enums/SettingKey.cs
https://github.com/SaiGonSoftware/Awesome-CMS-Core/issues/369
https://github.com/SaiGonSoftware/Awesome-CMS-Core/issues/374
Display user detail for index page
Allow admin to edit user info in portal
=> Acc profile

src/AwesomeCMSCore/AwesomeCMSCore/AwesomeCMSCore.csproj, src/AwesomeCMSCore/AwesomeCMSCore/package.json, src/AwesomeCMSCore/AwesomeCMSCore/webpack.config.js, src/AwesomeCMSCore/Modules/AwesomeCMSCore.Modules.Admin/Repositories/SettingsRepository.cs
=> small bug fix and add deployment script

Readme.md
Hi, I'm making updates for Open Collective. Either you or a supporter signed this repo up for Open Collective. This pull request adds backers and sponsors from your Open Collective https://opencollective.com/awesomecmscore❤️
It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [more info](https://github.com/opencollective/opencollective/wiki/Github-banner). See how it looks on this [repo](https://github.com/apex/apex#backers).
You can also add a postinstall script to let people know after npm|yarn install that you are welcoming donations (optional). [More info](https://github.com/OpenCollective/opencollective-cli)
You can …
=> Activating Open Collective
